<!DOCTYPE html><html lang="en"><head><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta charset="utf-8"><meta name="description" content="A page of my projects and such."><meta name="author" content="Chris “Kwpolska” Warrick"><title>{{ page.title }} — Kw’s GitHub Page</title><!-- Le styles --><link href="http://kwpolska.tk/assets/css/bootstrap.min.css" rel="stylesheet"><link href="http://kwpolska.tk/assets/css/code.css" rel="stylesheet"><link href="http://kwpolska.tk/assets/css/slides.css" rel="stylesheet"><link href="http://kwpolska.tk/assets/css/theme.css" rel="stylesheet"><link href="http://kwpolska.tk/assets/css/kw.css" rel="stylesheet"><link href="http://kwpolska.tk/assets/css/font-awesome.min.css" rel="stylesheet"><link href="http://kwpolska.tk/assets/css/bootstrap-responsive.min.css" rel="stylesheet"><link href="http://kwpolska.tk/assets/css/jquery.fancybox.css" rel="stylesheet" media="screen"><link href="http://kwpolska.tk/assets/css/jquery.fancybox-thumbs.css" rel="stylesheet" media="screen"><link href="http://kwpolska.tk/assets/css/jquery.fancybox-buttons.css" rel="stylesheet" media="screen"><!-- Le HTML5 shim, for IE6-8 support of HTML5 elements --><!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]--><link rel="alternate" type="application/rss+xml" title="RSS (en)" href="/rss.xml"><link rel="icon" href="/favicon.ico" sizes="16x16"><script src="http://kwpolska.tk/assets/js/jquery-1.7.2.min.js"></script></head><body>
<!-- Menubar -->
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">

        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

            <a class="brand" href="/">
            <img src="http://kwpolska.tk/assets/img/logo.png"> Kw’s GitHub Page
            </a>
            <!-- Everything you want hidden at 940px or less, place within here -->
            <div class="nav-collapse collapse">
                <ul class="nav"><li><a href="http://kwpolska.tk/">Kw’s Blog</a>
            </li><li><a href="/projects/">Projects</a>
            </li><li><a href="http://kwpolska.tk/contact/">Contact</a>

                </li></ul><ul class="nav pull-right"></ul></div>
        </div>
    </div>
</div>
<!-- End of Menubar -->
<div class="container-fluid" id="container-fluid">
    <!--Body content-->
    <div class="row-fluid">
    <div class="span2"></div>
    <div class="span8">

        <!--Body content-->
        <div class="postbox">
        <h1>{{ page.title }}</h1>

        {{ content }}
        <!--End of body content-->

    </div>
    </div>
    <!--End of body content-->
</div>
<div class="footerbox">
    <footer>served by <a href="https://pages.github.com/">github pages</a>, generated by
<a href="http://jekyllrb.com">jekyll</a><br>
copyright © 2009-2013 Kwpolska<br><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/">CC BY-NC-ND</a></footer></div>



<!-- asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
       change the UA-XXXXX-X to be your site's ID -->
<script>
    var _gaq = [['_setAccount', 'UA-11937989-3'], ['_trackPageview']];
    (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
    })(document, 'script');
</script><script src="http://kwpolska.tk/assets/js/jquery.colorbox-min.js"></script><script src="http://kwpolska.tk/assets/js/slides.min.jquery.js"></script><script src="http://kwpolska.tk/assets/js/bootstrap.min.js"></script><script src="http://kwpolska.tk/assets/js/jquery.mousewheel-3.0.6.pack.js"></script><script src="http://kwpolska.tk/assets/js/jquery.fancybox.pack.js"></script><script src="http://kwpolska.tk/assets/js/jquery.fancybox-buttons.js"></script><script src="http://kwpolska.tk/assets/js/jquery.fancybox-media.js"></script><script src="http://kwpolska.tk/assets/js/jquery.fancybox-thumbs.js"></script><script>
        $(document).ready(function() {
            $(".fancybox").fancybox();
        });
    </script></body></html>
